name: "Terraform Apply"

on:
  push:
    branches:
      - main

env: 
  PM_API_URL: ${{ secrets.PM_API_URL }}
  PM_API_TOKEN_ID: ${{ secrets.PM_API_TOKEN_ID }}
  PM_API_TOKEN_SECRET: ${{ secrets.PM_API_TOKEN_SECRET }}
  TF_VAR_cloud_init_pass: ${{ secrets.TF_VAR_CLOUD_INIT_PASS }}
  TF_VAR_cloud_init_user: ${{ secrets.TF_VAR_CLOUD_INIT_USER }}
  TF_VAR_sshkeys: ${{ secrets.TF_VAR_SSHKEYS }}

jobs:
  terraform:
    name: "Terraform Apply"
    runs-on: self-hosted
    permissions:
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Create TFVars
        run: |-
          cat << EOF > dev.tfvars
          pm_api_url          = "$PM_API_URL"
          pm_api_token_secret = "$PM_API_TOKEN_SECRET"
          ciuser              = "$TF_VAR_cloud_init_user"
          cipassword          = "$TF_VAR_cloud_init_pass"
          sshkeys             = "$TF_VAR_sshkeys"
          EOF
        working-directory: ./terraform/k8s

      - name: Terraform Init
        run: terraform init -var-file="dev.tfvars"
        working-directory: ./terraform/k8s

      - name: Terraform Apply
        run: terraform apply -auto-approve -var-file="dev.tfvars"
        working-directory: ./terraform/k8s