name: "Terraform Apply"

on:
  push:
    branches:
      - main

env: 
  PM_API_URL: ${{ secrets.PM_API_URL }}
  PM_API_TOKEN_ID: ${{ secrets.PM_API_TOKEN_ID }}
  PM_API_TOKEN_SECRET: ${{ secrets.PM_API_TOKEN_SECRET }}
  TF_VAR_cloud_init_pass: ${{ secrets.TF_VAR_CLOUD_INIT_PASS }}
  TF_VAR_cloud_init_user: ${{ secrets.TF_VAR_CLOUD_INIT_USER }}

jobs:
  terraform:
    name: "Terraform Apply"
    runs-on: self-hosted
    permissions:
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform/k8s

      - name: Terraform Apply
        run: terraform apply --auto-approve
        working-directory: ./terraform/k8s